name: "Setup Python Environment"
description: "Using uv setups python and additional tools"
inputs:
  python_version:
    required: false
    default: "3.9"
  install_tools:
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup Python
      shell: bash
      run: |
        echo "Setting up Python ${{ inputs.python_version }}..."
        uv python install ${{ inputs.python_version }}
        uv python pin ${{ inputs.python_version }}
        
        input_tools="${{ inputs.install_tools }}"

        clean_tools="${input_tools//$'\r'/}"

        if [[ -n "$clean_tools" ]]; then
          echo "Installing tools $clean_tools"

          while IFS= read -r tool; do
            echo "installing tool: $tool"
            read -r -a args <<< "$tool"
            uv tool install "${args[@]}"
          done <<< "${clean_tools%$'\n'}"

        else
          echo "No additional tools installed."
        fi

        echo "/github/home/.local/bin" >> "$GITHUB_PATH"