name: Validate Pull Request

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  run_tests:
    name: Run Testing
    runs-on: MA-Analytics-Runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Release
        uses: zilvertonz/shared-github-actions/version/github-release-validate@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_type: "infer_from_title"

      - name: Bash Scripts
        run: |
          bash deploy/common/discover-tf-versions.test.sh

      - name: Validate Markdown
        run: |
          # Convert README.md to index.md for vitepress
          find . -type f -name 'README.md' -exec bash -c 'mv $0 ${0/README/index}' {} \;
          npm add vitepress
          npx vitepress build
